#!/bin/sh

set -e
set -u

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

. "$SCRIPT_DIR/../settings"

sed -i \
  "/^CUSTOM_KERNEL_VERSION=/c\CUSTOM_KERNEL_VERSION=\"$VER_NUM-$DIST_NAME\"" \
  ${SCRIPT_DIR}/../config/hooks/normal/0001-create-initramfs-for-custom-kernel.hook.chroot

sed -i \
  "/^CUSTOM_KERNEL_VERSION=/c\CUSTOM_KERNEL_VERSION=\"$VER_NUM-$DIST_NAME\"" \
  ${SCRIPT_DIR}/../config/hooks/normal/0002-remove-other-kernels.hook.chroot

$SCRIPT_DIR/../scripts/000000-init
$SCRIPT_DIR/../scripts/000001-download-kernel-keys
$SCRIPT_DIR/../scripts/000002-download-kernel
$SCRIPT_DIR/../scripts/000003-extract-and-verify-kernel-download
$SCRIPT_DIR/../scripts/000004-install-kernel-build-dependencies
$SCRIPT_DIR/../scripts/000005-configure-kernel
$SCRIPT_DIR/../scripts/000006-build-kernel
$SCRIPT_DIR/../scripts/000007-copy-kernel-packages

CA_X509_CERT_FILE_DIRECTORY="$SCRIPT_DIR/../config/includes.chroot_after_packages/etc/pam_pkcs11/cacerts"
rm -rf "$CA_X509_CERT_FILE_DIRECTORY"
mkdir "$CA_X509_CERT_FILE_DIRECTORY"

CA_X509_CERT_FILE_RANDOMIZED_NAME="$(gpg --armor --gen-random 2 32 | tr -dc 'A-Za-z0-9_-').crt"
CA_X509_CERT_FILE_DESTINATION="$CA_X509_CERT_FILE_DIRECTORY/$CA_X509_CERT_FILE_RANDOMIZED_NAME"

if [ -f "$CA_X509_CERT_FILE_PATH" ]; then
  cp "$CA_X509_CERT_FILE_PATH" "$CA_X509_CERT_FILE_DESTINATION"
  chmod 444 "$CA_X509_CERT_FILE_DESTINATION"
else
  echo "ERROR: Set 'CA_X509_CERT_FILE_PATH' to a valid file path in the settings file located at $SCRIPT_DIR/settings"
  exit 1
fi

unset CA_X509_CERT_FILE_DIRECTORY

sed -i \
  "/^SMART_CARD_X509_CERT_SUBJECT_LINE=/c\SMART_CARD_X509_CERT_SUBJECT_LINE=\"$SMART_CARD_X509_CERT_SUBJECT_LINE\"" \
  "$SCRIPT_DIR/../config/hooks/normal/0800-smart-card-authentication-setup.hook.chroot"

lb build noauto \
  "${@}"

rm -rf "$CA_X509_CERT_FILE_DESTINATION"

unset CA_X509_CERT_FILE_RANDOMIZED_NAME
unset CA_X509_CERT_FILE_DESTINATION

$SCRIPT_DIR/../scripts/pre-commit-fixup
