#!/bin/sh

set -e
set -u

lb clean noauto "${@}"

rm -f config/binary
rm -f config/bootstrap
rm -f config/chroot
rm -f config/common
rm -f config/source

for arg in "$@"; do
  if [ "$arg" = "--purge" ]; then 
    rm -rf config/packages.chroot
    rm -rf tmp
  fi 
done
